name: Release

on:
  workflow_run:
    workflows: ["Versioning"]
    types:
      - completed
  pull_request:
    branches:
      - main

jobs:
  build-and-push:
    runs-on: ubuntu-22.04

    steps:
    - name: Checkpit code
      uses: actions/checkout@v3
      with:
        fetch-depth: 0 

    - name: Get Latest Tag
      id: get_version
      run: echo "VERSION=$(git describe --tags `git rev-list --tags --max-count=1`)" >> $GITHUB_ENV

    - name: Set up Docker Buildx
      uses: docker/setup-buildx-action@v2

    - name: Log in to GitHub Container Registry
      uses: docker/login-action@v2
      with:
        registry: ghcr.io
        username: ${{ github.actor }}
        password: ${{ github.token }}

    - name: Build and Push
      uses: docker/build-push-action@v5
      with:
        context: .
        file: ./Dockerfile
        push: true
        tags: |
          ghcr.io/${{ github.repository_owner }}/model-service:latest
          ghcr.io/${{ github.repository_owner }}/model-service:${{ env.VERSION }}

    - name: Job Completed
      run: echo "Docker Image pushed!"